### ISSUE TITLE
Remove lsp from emacs?

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/home-env#110]
I do not find the lsp works at all. Most of the time the font coloring is all screwed up. Now I'm getting these errors (below). I don't find it helpful at all, and we aren't using typescript so I vote to remove. @moellep @e-carlin ?

```txt
LSP :: Error from the Language Server: <semantic> TypeScript Server Error (5.1.6)
Cannot read properties of undefined (reading 'charCount')
TypeError: Cannot read properties of undefined (reading 'charCount')
    at LineNode.walk (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:183068:30)
    at LineIndex.edit (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182967:17)
    at _ScriptVersionCache._getSnapshot (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182773:31)
    at _ScriptVersionCache.lineOffsetToPosition (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182792:17)
    at TextStorage.lineOffsetToPosition (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:173042:22)
    at ScriptInfo.lineOffsetToPosition (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:173361:29)
    at IpcIOSession.getStartAndEndPosition (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182094:34)
    at IpcIOSession.getCodeFixes (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182046:49)
    at getCodeFixes (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:180188:43)
    at /home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182351:69
    at IpcIOSession.executeWithRequestId (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182343:14)
    at IpcIOSession.executeCommand (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182351:29)
    at IpcIOSession.onMessage (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:182393:51)
    at process.<anonymous> (/home/vagrant/.emacs.d/.cache/lsp/npm/typescript/lib/node_modules/typescript/lib/tsserver.js:183973:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:946:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) (Unknown error)
```

**Comment by moellep** [comment]
Yes, I agree.

**Comment by e-carlin** [comment]
I use it all day everyday and don't have problems. But, I use my personal config so happy to remove from bivio. I'll remove it.

**Comment by robnagler** [comment]
You must be using a different emacs than we are.
